name: Haxball Miami Host

on:
  workflow_dispatch:

jobs:
  run-host:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar Host de Haxball
        run: node bot.js
